### ISSUE TITLE
OpenAPI Generator not generating correct model for arrays

### ISSUE THREAD

**Issue by mario-subo** [sebgroup/frontend-tools#183]
**Describe the bug**
OpenAPI Generator is not generating correct model for some api responses (example: arrays)

**To Reproduce**
1. Generate api with swagger.json which included an api response of type `Array<SomeModel>`
2. Inspeact the generated API
3. The api in question is generated as AxiosResponse<SomeModel> instead of AxiosResponse<Array<SomeModel>>

**Expected behavior**
Should generate correct models.

**Additional context**
I changes the template from typescript-axios to typescript-fetch and it generates correctly

**Comment by omarVodiaK** [comment]
Can you post some swagger json to reproduce please ?
